import { PROGRAM_ID } from "./constants.js";

// ─── Config ───────────────────────────────────────────────────────────────────
const EXPLORER   = "https://api.provable.com/v2/testnet";
// Served from frontend/public/markets.json — the admin-controlled registry.
// Served from frontend/public/market-index.json (generated by indexer)
const INDEX_URL = "/markets-index.json";
const REGISTRY_URL = "/markets.json";

// ─── Fetch a single mapping value from chain ──────────────────────────────────
async function fetchMapping(name, key) {
  const cleanKey = key.toString().trim().endsWith('field') ? key : `${key}field`;
  try {
    const r = await fetch(`${EXPLORER}/program/${PROGRAM_ID}/mapping/${name}/${cleanKey}`, {
      signal: AbortSignal.timeout(5000),
    });
    if (!r.ok) return null;
    const v = await r.json();
    const s = (v.value?.toString() ?? v?.toString()).replace(/"/g, '').trim();
    if (s === 'true')  return true;
    if (s === 'false') return false;
    const m = s.match(/(-?\d+)/);
    return m ? +m[1] : null;
  } catch {
    return null;
  }
}

// ─── Fetch market state from chain ────────────────────────────────────────────
export async function fetchMarketOnChainState(marketId) {
  const [yesPool, noPool, vault, state, result, winPool] = await Promise.all([
    fetchMapping('yes_pools',      marketId),
    fetchMapping('no_pools',       marketId),
    fetchMapping('vault_balances', marketId),
    fetchMapping('market_states',  marketId),
    fetchMapping('market_results', marketId),
    fetchMapping('winning_pools',  marketId),
  ]);
  return {
    yes_pool:     yesPool  ?? 0,
    no_pool:      noPool   ?? 0,
    vault:        vault    ?? 0,
    state:        state    ?? 0,
    resolved:     state === 3,
    result:       result === true,
    winning_pool: winPool  ?? 0,
  };
}

async function fetchIndexedMarkets() {
  try {
    const r = await fetch(`${INDEX_URL}?t=${Date.now()}`);
    if (!r.ok) return null;
    const data = await r.json();
    return data.markets || [];
  } catch (e) {
    return null;
  }
}

async function fetchRegistry() {
  try {
    const r = await fetch(`${REGISTRY_URL}?t=${Date.now()}`); // bust cache
    if (!r.ok) throw new Error(`Registry fetch failed: ${r.status}`);
    const data = await r.json();
    if (!Array.isArray(data)) throw new Error("Registry is not an array");
    return data;
  } catch (e) {
    console.error("fetchRegistry error:", e);
    return [];
  }
}

// ─── Load all markets — the only function callers need ────────────────────────
// 1. Fetch the static registry (markets.json) or index if available
// 2. For each entry, verify it exists on-chain and get live pool state
// 3. Filter out any entries that are not yet confirmed on-chain
// 4. Return fully-formed market objects ready for the UI
export async function loadAllMarkets() {
  const [indexed, registry] = await Promise.all([
    fetchIndexedMarkets(),
    fetchRegistry(),
  ]);

  // Prefer indexed data (most performant)
  const source = (indexed && indexed.length > 0) ? indexed : registry;

  if (!source || source.length === 0) {
    console.warn("Market registry is empty or could not be loaded.");
    return [];
  }

  const results = await Promise.all(
    source.map(async (entry) => {
      const id = entry.marketId || entry.market_id;
      if (!id) {
        console.warn("Source entry missing market_id:", entry);
        return null;
      }

      // Ensure id format is clean
      const idStr = String(id);
      const cleanId = idStr.replace(/\.private$|\.public$/, "").trim();

      try {
        const chain = await fetchMarketOnChainState(cleanId);
        if (!chain) {
          console.warn(`market_states[${cleanId}] returned null`);
        }

      return {
        // React key + identifier
        id:              cleanId,
        market_id:       cleanId,
        // Static metadata from source
        question:        entry.question        || entry.metadata?.question || null,
        description:     entry.description     || entry.metadata?.description || null,
        category:        entry.category        || entry.metadata?.category || "General",
        image:           entry.image           || entry.metadata?.image || null,
        resolution_time: entry.resolution_time || entry.metadata?.resolution_time || 0,
        metadata_cid:    entry.metadata_cid    || null,
        source_of_truth: entry.source_of_truth || null,
        // Live on-chain state — fall back to zeros if API unavailable
        yes_pool:        chain?.yes_pool     ?? 0,
        no_pool:         chain?.no_pool      ?? 0,
        vault:           chain?.vault        ?? 0,
        state:           chain?.state        ?? 0,
        resolved:        chain?.resolved     ?? false,
        result:          chain?.result       ?? false,
        winning_pool:    chain?.winning_pool ?? 0,
        };
      } catch (e) {
        console.error(`Error loading market ${cleanId}:`, e);
        return null;
      }
    }),
  );

  return results.filter(Boolean);
}

// ─── Legacy alias ─────────────────────────────────────────────────────────────
export const loadDeployedMarkets = loadAllMarkets;
